export const LOAD_PRODUCTS = 'LOAD_PRODUCTS'

export const LOAD_WORK_PRODUCTS = 'LOAD_WORK_PRODUCTS'

export const LOAD_FIRE_PRODUCTS = 'LOAD_FIRE_PRODUCTS'

export const LOAD_HERITAGE_PRODUCTS = 'LOAD_HERITAGE_PRODUCTS'

export const ADD_TO_CART   = 'ADD_TO_CART'

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export const SAVE_FOR_LATER = 'SAVE_FOR_LATER'

export const REMOVE_FROM_SAVED = 'REMOVE_FROM_SAVED'

export const CHANGE_PRODUCT_QUANTITY = 'CHANGE_PRODUCT_QUANTITY'

export const SET_SHOW = 'SET_SHOW'